<?php

use Illuminate\Database\Seeder;

class SeedFurnitureTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //sofa
        DB::table('furniture')->insert([
            'category_id' => 1,
            'manufacturer_id' => 1,
            'material_id' => 2,
            'name' => 'Ballinasloe 3 Piece LAF Sectional',
            'price' => 1700.99,
            'depth' => '92.0"',
            'height' => '39.0"',
            'width' => '143.0"',
            'cost' => 1700.99,
            'description' => 'A mastery in less is more, the Ballinasloe 3-piece sectional manages to make cool, contemporary design so warm and cozy. A new twist on neutral, the sectional’s soothing “smoky” gray upholstery is incredibly plush to the touch. Gently rounded corners give the clean-lined profile a sense of ease, for a high-style look that’s ultra inviting.',
            'color' => 'Gray',
            'image' => '/images/furniture/Ballinasloe-3-Piece-LAF-Sectional.jpg',
            'SKU' => '0000123456',
            'in_stock' => 'Out of Stock'
        ]);
        DB::table('furniture')->insert([
            'category_id' => 1,
            'manufacturer_id' => 1,
            'material_id' => 1,
            'name' => 'Altonbury Sofa',
            'price' => 1809.99,
            'depth' => '37.0"',
            'height' => '36.0"',
            'width' => '82.0"',
            'cost' => 1809.99,
            'description' => 'Tailor your space with the tidy structure of the Altonbury sofa. Decorative stitching and button tufting on the box cushion make for a very neat appearance. With real leather covering the seating area—where it matters most—this piece has skillfully matched leather elsewhere, so you won’t get hemmed in by the price.',
            'color' => 'Blue',
            'image' => '/images/furniture/Altonbury-Sofa.jpg',
            'SKU' => '0000123654',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 1,
            'manufacturer_id' => 1,
            'material_id' => 2,
            'name' => 'Darcy Sofa',
            'price' => 2700.99,
            'depth' => '39.0"',
            'height' => '40.0"',
            'width' => '89.0"',
            'cost' => 1900.99,
            'description' => 'Talk about fine lines and great curves. That’s the beauty of the Darcy sofa—made to suit your appreciation for clean, contemporary style. A striking flared frame, comfy pillow top armrests and an ultra-soft upholstery that holds up to everyday living complete this fashion statement. Frame constructions have been tested with various equipment to simulate the home and transportation environments to insure durability. Corners are glued, blocked and stapled. Seats and back spring rails are cut from 78” hardwood. Stripes and patterns are match cut. All fabrics are pre-approved for wearability and durability against AHFA standards. Cushion cores are constructed of low melt fiber wrapped over high quality foam.',
            'color' => 'Black',
            'image' => '/images/furniture/Darcy-Sofa.jpg',
            'SKU' => '0000123564',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 1,
            'manufacturer_id' => 1,
            'material_id' => 2,
            'name' => 'Enderlin Sofa',
            'price' => 2300.99,
            'depth' => '38.0"',
            'height' => '36.0"',
            'width' => '82.0"',
            'cost' => 2000.99,
            'description' => 'A brilliant take on urban chic styling, the Enderlin sofa in vibrant blue makes high design highly affordable. Distinctive elements include quilted channel stitching for clean-lined allure and a velvety soft fabric you\'ll love living with. Sculptural track arms up the wow factor. If you’re looking for big style on more modest scale, you’re sure to appreciate this sofa’s space-conscious 82" wide profile.',
            'color' => 'Blue',
            'image' => '/images/furniture/Enderlin-Sofa.jpg',
            'SKU' => '0000123546',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 1,
            'manufacturer_id' => 1,
            'material_id' => 1,
            'name' => 'Morelos Sofa',
            'price' => 2500.99,
            'depth' => '38.0"',
            'height' => '37.0"',
            'width' => '85.0"',
            'cost' => 2500.99,
            'description' => 'When it comes to style, less is more with this fashion-forward sofa. Taking minimalism to the max, it wows with a crisp, clean profile, sleek track arms and a simplified 2-over-2 cushion design. Dressed to impress those who demand the best, this ultra-contemporary sofa sports real leather throughout the seating area for incomparable comfort.',
            'color' => 'Black',
            'image' => '/images/furniture/Morelos-Sofa.jpg',
            'SKU' => '0000456789',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 1,
            'manufacturer_id' => 1,
            'material_id' => 2,
            'name' => 'Alenya Sofa',
            'price' => 2807.99,
            'depth' => '37.0"',
            'height' => '38.0"',
            'width' => '84.0"',
            'cost' => 1800.99,
            'description' => 'The sleek mid-century lines of the Alenya sofa are always in vogue. With neatly tailored box cushions and track arms, the microfiber upholstered sofa is supremely comfortable and stylish. Tonal piping and a pair of printed pillows further refine the silhouette. Frame constructions have been rigorously tested to simulate the home and transportation environments for improved durability. Corners are glued, blocked and stapled. Seats and back spring rails are cut from 78” hardwood. Stripes and patterns are match cut. All fabrics are pre-approved for wearability and durability against AHFA standards. Cushion cores are constructed of low melt fiber wrapped over high quality foam.',
            'color' => 'Green',
            'image' => '/images/furniture/Alenya-Sofa.jpg',
            'SKU' => '0000786524',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 1,
            'manufacturer_id' => 1,
            'material_id' => 1,
            'name' => 'Sissoko Sofa',
            'price' => 2909.99,
            'depth' => '37.0"',
            'height' => '37.0"',
            'width' => '84.0"',
            'cost' => 2909.99,
            'description' => 'Striking a pose with ultra-mod style and distinctive European flair, the Sissoko sofa in gray is beauty without compromise. Rest assured, the sofa\'s seating area is wrapped in real leather for your pleasure. The highly structural profile is enhanced with channel stitching, button tufting and wraparound pillow top armrests for a richly tailored aesthetic that’s cool from every angle.',
            'color' => 'Brown',
            'image' => '/images/furniture/Sissoko-Sofa.jpg',
            'SKU' => '0000743455',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 1,
            'manufacturer_id' => 1,
            'material_id' => 2,
            'name' => 'Dorsten Sofa Chaise',
            'price' => 2210.99,
            'depth' => '62.0"',
            'height' => '38.0"',
            'width' => '92.0"',
            'cost' => 1100.99,
            'description' => 'The Dorsten sofa chaise has the corner on ultra-contemporary style made for easy, everyday living. Upholstered in a plush slate chenille, it takes neutral sophistication to another level. And talk about accommodating. Thanks to a versatile chaise with movable ottoman and reversible seat cushions, you can enjoy the chaise on either side to suit your space.',
            'color' => 'Gray',
            'image' => '/images/furniture/Dorsten-Sofa-Chaise.jpg',
            'SKU' => '0000156782',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 1,
            'manufacturer_id' => 1,
            'material_id' => 2,
            'name' => 'Harelson Sofa',
            'price' => 2430.99,
            'depth' => '41.0"',
            'height' => '40.0"',
            'width' => '100.0"',
            'cost' => 1400.99,
            'description' => 'True classic character comes to life in this sofa. Set back pleated rolled arms and warm brown exposed frame with bun feet are beautifully traditional. Lovely detailing carries itself through the herringbone weave in the soft upholstery. Seat cushions reverse to maintain durable comfort. Vintage-inspired jumbo nailhead trim graces the design. Plaid and botanical pillows in dark brown are a timeless touch.',
            'color' => 'Wheat',
            'image' => '/images/furniture/Harelson-Sofa.jpg',
            'SKU' => '0000895742',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 1,
            'manufacturer_id' => 1,
            'material_id' => 2,
            'name' => 'Larkinhurst Sofa',
            'price' => 3205.99,
            'depth' => '39.0"',
            'height' => '38.0"',
            'width' => '89.0"',
            'cost' => 3205.99,
            'description' => 'Dramatically transform your living space with the rustic look of weathered leather you love—at a fraction of the cost. That’s the beauty of the Larkinhurst faux leather sofa. Washed in earthy Southwestern tones, with generous back and seating support and jumbo window-pane stitching—it envelopes you in comfort and quality. Classic elements such as rolled arms and turned feet bring in just enough traditional touch. Frame constructions have been tested with various equipment to simulate the home and transportation environments to insure durability. Corners are glued, blocked and stapled. Seats and back spring rails are cut from 78” hardwood. Stripes and patterns are match cut. All fabrics are pre-approved for wearability and durability against AHFA standards. Style features reversible coil seating and pillows with feather inserts and hidden zippers.',
            'color' => 'Brown',
            'image' => '/images/furniture/Larkinhurst-Sofa.jpg',
            'SKU' => '0000246801',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 1,
            'manufacturer_id' => 1,
            'material_id' => 2,
            'name' => 'Monaghan- EXCLUSIVE Sofa',
            'price' => 1609.99,
            'depth' => '45.0"',
            'height' => '39.0"',
            'width' => '98.0"',
            'cost' => 1609.99,
            'description' => 'This sofa strikes a beautiful balance between classic and current. Traditional elements include t-cushion seating and setback roll arms, angled for modern flair. Posh collection of pillows in spa mist and jacquard paisley make a muted, mellow complement to the sofa’s casual textured chenille upholstery. Choice of sandstone beige is a light and lovely style awakening.',
            'color' => 'Sandstone',
            'image' => '/images/furniture/Monaghan--EXCLUSIVE-Sofa.jpg',
            'SKU' => '0000246802',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 1,
            'manufacturer_id' => 1,
            'material_id' => 1,
            'name' => 'Bladen Sofa',
            'price' => 705.99,
            'depth' => '36.0"',
            'height' => '38.0"',
            'width' => '90.0"',
            'cost' => 705.99,
            'description' => 'If you love the cool look of leather but long for the warm feel of fabric, you’ll find the Bladen sofa fits the bill beautifully. Rest assured, the textural, multi-tonal upholstery is rich with character and interest—while plush, pillowy cushions merge comfort and support with a high-style design. Frame constructions have been rigorously tested to simulate the home and transportation environments for improved durability. Corners are glued, blocked and stapled. Seats and back spring rails are cut from 78” hardwood. Stripes and patterns are match cut. All fabrics are pre-approved for wearability and durability against AHFA standards. Cushion cores are constructed of low melt fiber wrapped over high quality foam.',
            'color' => 'Coffee',
            'image' => '/images/furniture/Bladen-Sofa.jpg',
            'SKU' => '0000246803',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 1,
            'manufacturer_id' => 1,
            'material_id' => 1,
            'name' => 'Hettinger Sofa',
            'price' => 1405.99,
            'depth' => '38.0"',
            'height' => '36.0"',
            'width' => '79.0"',
            'cost' => 900.99,
            'description' => 'You could easily spend an arm and a leg for high-end leather furniture. We say the heck with that. Rest assured, the Hettinger sofa entices with real leather, rich with natural grain and a dry matte aesthetic for subtle sophistication. The seating area is covered in genuine leather where it matters most. Skillfully matched faux leather on the exterior keeps the price incomparably affordable. Minimalist elements include a 2-over-2 cushion design, tapered feet and t-cushions wrapping the slim track arms to soften the linear look just a touch.',
            'color' => 'Brown',
            'image' => '/images/furniture/Hettinger-Sofa.jpg',
            'SKU' => '0000246804',
        ]);
        //Chair
        DB::table('furniture')->insert([
            'category_id' => 2,
            'manufacturer_id' => 2,
            'material_id' => 2,
            'name' => 'Wightman Slipper Chair',
            'price' => 140.99,
            'depth' => '22.0"',
            'height' => '32.0"',
            'width' => '29.0"',
            'cost' => 60.99,
            'description' => 'This chic slipper accent chair will effortlessly add character to your living room, workspace and beyond. Choose from blue, grey, red or yellow upholstery, with a comfortably cushioned seat, durable frame construction, and espresso-finished classic wooden legs.',
            'color' => 'Red',
            'image' => '/images/furniture/wightman.jpg',
            'SKU' => '0000246816',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 2,
            'manufacturer_id' => 2,
            'material_id' => 2,
            'name' => 'Roswell Lounge Chair',
            'price' => 330.99,
            'depth' => '29.0"',
            'height' => '32.0"',
            'width' => '27.0"',
            'cost' => 330.99,
            'description' => 'Lend any seating arrangement with a polished hand and spare seat, with this accent chair. Perfectly at home in contemporary aesthetics, the frame of this piece is crafted from solid wood in a medium espresso finish, and upholstered with a polyester blend in a solid hue that is filled with foam. It features a cushioned back and flared arms. To care for this piece, we recommend only spot cleaning as needed.',
            'color' => 'White',
            'image' => '/images/furniture/roswell.jpg',
            'SKU' => '0000246815',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 2,
            'manufacturer_id' => 2,
            'material_id' => 1,
            'name' => 'Ensa Barrel Chair',
            'price' => 205.99,
            'depth' => '28.0"',
            'height' => '26.0"',
            'width' => '28.0"',
            'cost' => 100.99,
            'description' => 'Drawing on the elegance and attitude of classic design, it has a simplified profile with soft curves and sheltering arms. Where also adds a splash of sophisticated style to any decor, the clean silhouette wraps around your body to create an irresistible spot for reading or enjoying a cozy chat. Meticulously hand-applied nail heads grace the perimeter for a final touch.',
            'color' => 'Brown',
            'image' => '/images/furniture/ensa.jpg',
            'SKU' => '0000246813',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 2,
            'manufacturer_id' => 2,
            'material_id' => 1,
            'name' => 'Wilmore Swivel 22" Barrel Chair',
            'price' => 293.99,
            'depth' => '29.0"',
            'height' => '30.0"',
            'width' => '30.0"',
            'cost' => 293.99,
            'description' => 'Perfect for rounding out your living ensemble with a handy spare perch, an accent chair like this is a great spot to curl up in while helping expand your home\'s style. Defined by a deep barrel design, this piece features a pine wood frame wrapped in faux leather. Perfect for an understated modern accent, this sleek armchair also showcases a swivel base, so you can easily reposition it for your comfort.',
            'color' => 'White',
            'image' => '/images/furniture/wilmore.jpg',
            'SKU' => '0000246812',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 2,
            'manufacturer_id' => 2,
            'material_id' => 1,
            'name' => 'Gaynell Barrel Chair',
            'price' => 280.99,
            'depth' => '28.0"',
            'height' => '32.0"',
            'width' => '31.0"',
            'cost' => 170.99,
            'description' => 'More than just a spot to sit, this armchair adds style to your ensemble! Put it to work in the living room as a worthy accent to your sofa, or let it take up a corner of your restful retreat to complete the aesthetic. Its manufactured wood frame takes on a barrel shape and features foam padding and plastic legs.',
            'color' => 'Black',
            'image' => '/images/furniture/gaynell.jpg',
            'SKU' => '0000246811',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 2,
            'manufacturer_id' => 2,
            'material_id' => 2,
            'name' => 'Galewood Wood Leg Upholstered Dining Chair',
            'price' => 229.99,
            'depth' => '24.0"',
            'height' => '40.0"',
            'width' => '20.0"',
            'cost' => 229.99,
            'description' => 'Dress up your dining room for an upcoming dinner party or round out a breakfast nook ensemble with this stylish side chair. Founded atop four legs finished in black, its frame is crafted from solid rubberwood. Foam padding lends comfort to the seat, while polyester upholstery in a solid hue wraps around to tie it all together. Plus, there\'s nailhead trim lining the base for a pop of polish.',
            'color' => 'Gray',
            'image' => '/images/furniture/galewood.jpg',
            'SKU' => '0000246810',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 2,
            'manufacturer_id' => 2,
            'material_id' => 2,
            'name' => 'Senoia 19" Armchair',
            'price' => 340.99,
            'depth' => '30.0"',
            'height' => '31.0"',
            'width' => '25.0"',
            'cost' => 340.99,
            'description' => 'Whether you\'re complementing a contemporary aesthetic in the den or injecting an inviting entertainment space with a dash of midcentury modern flair, this bold arm chair is a stylish accent in your well-appointed space. Featuring a clean-lined silhouette with gently splayed, birch wood legs and subtle button tufts, this arm chair has all the hallmarks of classic turn-of-the-century looks. Let a pair flank a round-top table over a geometric rug to offset the set\'s low-key look, then add in a pair of complementing throw pillows to tie it all together.',
            'color' => 'Blue',
            'image' => '/images/furniture/senoia.jpg',
            'SKU' => '0000246814',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 2,
            'manufacturer_id' => 2,
            'material_id' => 2,
            'name' => 'Trent 24.5" Side Chair',
            'price' => 195.99,
            'depth' => '20.0"',
            'height' => '17.0"',
            'width' => '25.0"',
            'cost' => 100.99,
            'description' => 'A stylish spare seat, reading nook chair, you name it, this slipper chair invites you to kick back wherever it lives. Its clean, Euro look and mid-century legs bring a relaxed, modern feel to your home. The solid wood frame is wrapped in polyester blend upholstery, complete with channel-stitch details, and padded with foam fill. Tapered wood legs, finished in black, round out the design below. Plus, this chair’s armless seatback leaves plenty of elbow room for existing furniture.',
            'color' => 'White',
            'image' => '/images/furniture/trent.jpg',
            'SKU' => '0000246809',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 2,
            'manufacturer_id' => 2,
            'material_id' => 2,
            'name' => 'Halesworth Armchair',
            'price' => 330.99,
            'depth' => '30.0"',
            'height' => '33.0"',
            'width' => '31.0"',
            'cost' => 160.99,
            'description' => 'A flared, button tufted back and loose seat nestled in this classic frame make this chair a charming addition to your living space. Wrapped roll arms and box seat piping back make the styling complete; every detail thought of.',
            'color' => 'Blue',
            'image' => '/images/furniture/halesworth.jpg',
            'SKU' => '0000246808',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 2,
            'manufacturer_id' => 2,
            'material_id' => 2,
            'name' => 'Brittnie Barrel Chair',
            'price' => 175.99,
            'depth' => '29.0"',
            'height' => '31.0"',
            'width' => '22.0"',
            'cost' => 90.99,
            'description' => 'This chair combines the traditional and classic style, which are perfect for your restaurant, living room, coffee house, patio, bedroom, or any other decor theme, an ergonomic oversized chair, designed for comfort, durability, and impeccable style.',
            'color' => 'White',
            'image' => '/images/furniture/brittnie.jpg',
            'SKU' => '0000246807',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 2,
            'manufacturer_id' => 2,
            'material_id' => 1,
            'name' => 'Marta Barrel Chair',
            'price' => 1165.99,
            'depth' => '61.0"',
            'height' => '37.0"',
            'width' => '61.0"',
            'cost' => 600.99,
            'description' => 'Whether you love curling up beside loved ones or you prefer lots of elbow room as you lounge, this oversized barrel chair is the perfect pick for your home. Spanning 61" wide, this piece is crafted with a solid wood and plywood frame, foam and synthetic fibre fill, and polyester-blend upholstery in a solid hue for an understated and approachable look. A toss pillow is included to make this seat even more inviting. Best of all, no assembly is required.',
            'color' => 'Gray',
            'image' => '/images/furniture/marta.jpg',
            'SKU' => '0000246806',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 2,
            'manufacturer_id' => 2,
            'material_id' => 1,
            'name' => 'Munson Barrel Chair',
            'price' => 175.99,
            'depth' => '23.0"',
            'height' => '29.0"',
            'width' => '26.0"',
            'cost' => 175.99,
            'description' => 'Add stylish extra seating with this Fabric Club chair. Boasting a sophisticated design, This contemporary tub chair features flared arms to provide your guests with a sturdy, comfortable place to rest their arms throughout their visit.',
            'color' => 'Black',
            'image' => '/images/furniture/munson.jpg',
            'SKU' => '0000246805',
        ]);
        //newly added by suelian/5aug
        DB::table('furniture')->insert([
            'category_id' => 4,
            'manufacturer_id' => 2,
            'material_id' => 9,
            'name' => 'Devito Cross Legs Coffee Table',
            'price' => 179.99,
            'depth' => '22.0"',
            'height' => '18.0"',
            'width' => '42.0"',
            'cost' => 99.99,
            'description' => 'Whether the surface for a game night or just the perfect perch for keeping cups in easy reach, this coffee table is an essential place to gather in your living room ensemble. Crafted from metal, it features an X-shaped base with clean lines for a touch of contemporary appeal, while neutral hues allow it to blend with your colour scheme. The manufactured wood top showcases a rectangular silhouette and can support up to 125 pounds after assembly.',
            'color' => 'Grey',
            'image' => '/images/furniture/cross_coffee_table.jpg',
            'SKU' => '0000946804',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 4,
            'manufacturer_id' => 3,
            'material_id' => 9,
            'name' => 'Brierfield 3 Legs 2 Nesting Tables',
            'price' => 159.99,
            'depth' => '38.0"',
            'height' => '18.0"',
            'width' => '34.0"',
            'cost' => 89.99,
            'description' => 'A nesting coffee table with a set of two rounded triangular shapes featuring mixed material tabletops. Add a touch of mid-century style to any living room with these unique coffee tables or end tables. The lower table features a rich textured walnut paper, while the smaller floating table boasts an elegant faux white Carrara marble top. The smaller side table nests inside the larger coffee table for small spaces or the two tables can be arranged separately for the maximum table-space.',
            'color' => 'Walnut/White Marble',
            'image' => '/images/furniture/brierfield_table.jpg',
            'SKU' => '0000946803',
        ]);        
        DB::table('furniture')->insert([
            'category_id' => 3,
            'manufacturer_id' => 1,
            'material_id' => 10,
            'name' => 'Forest Park Retro Coffee Table',
            'price' => 262.00,
            'depth' => '35.0"',
            'height' => '17.0"',
            'width' => '35.0"',
            'cost' => 120.00,
            'description' => 'Bring a streamlined modern style to your seating ensemble with this retro coffee table. Crafted from manufactured wood with laminate veneers in a rich woodgrain finish, this table strikes a round silhouette with a smooth, thick edge. Four powder-coated metal hairpin legs complete the design. It is crafted in mid-century design, the retro round coffee table offers an industrial feel for your living room',
            'color' => 'Black',
            'image' => '/images/furniture/forest_table.jpg',
            'SKU' => '0000946802',
        ]); 
        DB::table('furniture')->insert([
            'category_id' => 1,
            'manufacturer_id' => 2,
            'material_id' => 2,
            'name' => 'Avoca Tufted Cocktail Ottoman',
            'price' => 425.99,
            'depth' => '35.0"',
            'height' => '17.0"',
            'width' => '35.0"',
            'cost' => 220.00,
            'description' => "Perfect for a spot to put your feet up, spare perch when seating's scarce, or coffee table stand-in, an ottoman like this is a versatile addition to almost any space. Crafted from a manufactured wood frame, this piece features a solid-hued polyester blend upholstery for an understated look in any space. Button tufting and turned feet round this piece out with classic touches.",
            'color' => 'Dark Blue',
            'image' => '/images/furniture/avoca_sofa.jpg',
            'SKU' => '0000946801',
        ]);   
        DB::table('furniture')->insert([
            'category_id' => 3,
            'manufacturer_id' => 3,
            'material_id' => 10,
            'name' => 'Wilson Console Table',
            'price' => 309.99,
            'depth' => '13.0"',
            'height' => '30.0"',
            'width' => '35.0"',
            'cost' => 309.99,
            'description' => "Add antique charm and fill you to your space with this beautiful Wilson Solid Wood Console Table. Inspired by classic vintage design and compact in build, this console table emphasizes detailed wood carving that will add instant charm, will fitting seamlessly in the empty spaces in your room or hallways. The solid Acacia wood construction makes for sound stability and has been carefully smoothed and lacquered for heightened wear resistance. Spacious dual front-facing drawers can stow away your belongings, keeping them readily available and out of sight, while the base shelf allows for additional storage for décor or items like shoes, books and more.",
            'color' => 'Ivory White',
            'image' => '/images/furniture/wilson_table.jpg',
            'SKU' => '0000946800',
        ]);    
        DB::table('furniture')->insert([
            'category_id' => 3,
            'manufacturer_id' => 1,
            'material_id' => 9,
            'name' => 'Arsenault Console Table',
            'price' => 269.99,
            'depth' => '12.0"',
            'height' => '30.0"',
            'width' => '46.0"',
            'cost' => 269.99,
            'description' => "Bring a refined rustic style to your space with this console table. Crafted of manufactured wood with laminate wood-grain veneers for a reclaimed wood aesthetic, this console table strikes a clean-lined rectangular silhouette on four straight square legs. Blackened bronze metal corner accents and X-frame sides offer a rustic complement, while an open lower shelf is perfect for stacking go-to books, displaying framed photos, or larger decor items.",
            'color' => 'Reclaimed Barnwood',
            'image' => '/images/furniture/arsenalut_table.jpg',
            'SKU' => '0000946799',
        ]);    
        DB::table('furniture')->insert([
            'category_id' => 3,
            'manufacturer_id' => 2,
            'material_id' => 9,
            'name' => 'Nena Console Table',
            'price' => 459.99,
            'depth' => '13.0"',
            'height' => '30.0"',
            'width' => '42.0"',
            'cost' => 220.00,
            'description' => "This entry table has the best of both worlds when it comes to storage. Half is an open cubby while the other half is covered by a slatted drop-down door. This long accent table has a unique powder-coated metal base that complements the boxy silhouette of the top compartment. Round out this modern slat door collection by pairing this sofa table with its matching side table, TV stand, or coffee table.",
            'color' => 'Dark Walnut',
            'image' => '/images/furniture/nena_table.jpg',
            'SKU' => '0000946798',
        ]); 
        DB::table('furniture')->insert([
            'category_id' => 3,
            'manufacturer_id' => 3,
            'material_id' => 9,
            'name' => 'Trinidad Console Table',
            'price' => 291.99,
            'depth' => '12.0"',
            'height' => '32.0"',
            'width' => '48.0"',
            'cost' => 150.00,
            'description' => "Whether it’s used in the entryway, hall, or living room, this console table is a great way to add both style and storage to your space. Its black metal frame strikes a slim silhouette to pair well with modern spaces, while the manufactured wood top sports a wood grain finish for a touch of natural appeal. Two drawers let you tuck away small-scale accents and anything you need out of sight but close at hand.",
            'color' => 'Light Brown',
            'image' => '/images/furniture/trinidad_table.jpg',
            'SKU' => '0000946797',
        ]);            
        DB::table('furniture')->insert([
            'category_id' => 3,
            'manufacturer_id' => 1,
            'material_id' => 9,
            'name' => 'Dexter Solid Wood Console Table',
            'price' => 199.99,
            'depth' => '12.0"',
            'height' => '32.0"',
            'width' => '48.0"',
            'cost' => 100.00,
            'description' => "This Dexter Console Table is full of character with the real wood design. Made to tie in with your unique style easily, this table is the perfect stage for your photos and decor. Dress it up or dress it down, the tones and clean lines make for a great centerpiece in your living room, dining room, or entryway. This table comes fully assembled and ready to decorate.",
            'color' => 'Dark Walnut',
            'image' => '/images/furniture/dexter_table.jpg',
            'SKU' => '0000946796',
        ]);   
        DB::table('furniture')->insert([
            'category_id' => 3,
            'manufacturer_id' => 2,
            'material_id' => 10,
            'name' => 'Marceline Farmhouse Console Table',
            'price' => 289.99,
            'depth' => '13.0"',
            'height' => '32.0"',
            'width' => '40.0"',
            'cost' => 140.00,
            'description' => "Farmhouse inspired design will add a charming rustic touch to any room with this Farmhouse Console Table.",
            'color' => 'Dark Walnut',
            'image' => '/images/furniture/marceline_table.jpg',
            'SKU' => '0000946795',
        ]);  
        DB::table('furniture')->insert([
            'category_id' => 3,
            'manufacturer_id' => 3,
            'material_id' => 10,
            'name' => 'Rosas Console Table',
            'price' => 319.99,
            'depth' => '14.0"',
            'height' => '32.0"',
            'width' => '32.0"',
            'cost' => 319.99,
            'description' => "A platform for your home’s personality, console tables are designed to greet guests with carefully curated displays of family photos, potted plants, and more. This one, for example, brings classic style to your abode with its clean-lined silhouette and slatted lower shelf. Crafted from a blend of solid and manufactured wood, it sports four panelled drawers with cup pulls and boasts a solid colour.",
            'color' => 'Black',
            'image' => '/images/furniture/rosas_table.jpg',
            'SKU' => '0000946794',
        ]);  
        DB::table('furniture')->insert([
            'category_id' => 3,
            'manufacturer_id' => 1,
            'material_id' => 9,
            'name' => 'Union Point Console Table',
            'price' => 115.99,
            'depth' => '12.0"',
            'height' => '29.0"',
            'width' => '31.0"',
            'cost' => 70.00,
            'description' => "The contemporary modern design of the console table is suitable for every room of your house. This table is versatile in both use and design. It is a stylish piece to add with its functionality and on-trend look. Simple in silhouette yet has a sturdy construction, this console table has a spacious top and will add a clean and elegant feel complementing any home décor.",
            'color' => 'White',
            'image' => '/images/furniture/union_table.jpg',
            'SKU' => '0000946793',
        ]);    
        DB::table('furniture')->insert([
            'category_id' => 3,
            'manufacturer_id' => 2,
            'material_id' => 9,
            'name' => 'Spector Console Table',
            'price' => 152.99,
            'depth' => '13.0"',
            'height' => '24.0"',
            'width' => '40.0"',
            'cost' => 70.00,
            'description' => "Stylish Console with retro wood tones and modern metal frame, this 2 tier console table will compliment your furniture, bringing function and fresh appeal to the space you place it. Except using it as a hallway/entryway table to decorate your living area, this piece of furniture is also wide enough to work as a TV stand/media entertainment centre for flat screen TV, cable box and game consoles. This accent console table is designed with roomy tabletop for your daily necessities. The bottom wooden shelf provides additional space to place ornaments, containers and with strong metal frame and 0.75” thick particle board, this vintage entryway table can ensure large weight capacity and long lasting for many years to come. We devote ourselves to design furniture that can truly update your life, that is why we design adjustable levelling feet on the bottom of this table to prevent scratching the floor and keep stability.",
            'color' => 'Light Brown',
            'image' => '/images/furniture/spector_table.jpg',
            'SKU' => '0000946792',
        ]);       
        DB::table('furniture')->insert([
            'category_id' => 3,
            'manufacturer_id' => 3,
            'material_id' => 10,
            'name' => 'Oneill Solid Wood Dining Table',
            'price' => 459.99,
            'depth' => '42.0"',
            'height' => '30.0"',
            'width' => '42.0"',
            'cost' => 220.00,
            'description' => "Some of our best memories are created at our dining tables – they host our family dinners, holiday feasts and more. No matter the shape or size, they play an integral role in our home. Take this one for example: Crafted from rubberwood, it features an eye-catching pedestal base with turned detailing that offers a touch of traditional appeal. Its tabletop showcases a round silhouette and can seat up to four people after assembly.",
            'color' => 'Black',
            'image' => '/images/furniture/oneill.jpg',
            'SKU' => '0000946791',
        ]);   
        DB::table('furniture')->insert([
            'category_id' => 4,
            'manufacturer_id' => 1,
            'material_id' => 9,
            'name' => 'Hermitage Solid Wood Dining Table',
            'price' => 559.99,
            'depth' => '45.0"',
            'height' => '30.0"',
            'width' => '45.0"',
            'cost' => 390.00,
            'description' => "Bring traditional style to your dining room with this table, the perfect piece to act as the focal point of your ensemble! Crafted from solid wood, it stands atop a pedestal-style base with carved details and a solid finish, while the circular top and matching apron sport an oak hue with grain patterns for a contrasting touch. Measuring 45'' L x 45'' W x 30'' H, it seats up to four for a home-cooked meal.",
            'color' => 'Dark Sea Green',
            'image' => '/images/furniture/hermitage.jpg',
            'SKU' => '0000946790',
        ]);     
        DB::table('furniture')->insert([
            'category_id' => 4,
            'manufacturer_id' => 2,
            'material_id' => 10,
            'name' => 'Ridgley Extendable Acacia Solid Wood Dining Table',
            'price' => 899.99,
            'depth' => '42.0"',
            'height' => '30.0"',
            'width' => '60.0"',
            'cost' => 899.99,
            'description' => "From holiday get-togethers, to weekly dinners with your family, this extendable dining table gives you the right place to sit whatever the occasion. Complete with one table and one removable leaf, this oval-shaped table comes crafted from solid acacia wood and features a two-tone, wire-brushed finish that highlights its natural wood grain. Tapered legs lends this piece a classic touch, while a pedestal base adds to its traditional look and feel. When collapsed, this table can accommodate four guests, but adding the leaf gives you room for six of your loved ones.",
            'color' => 'Weathered Russet',
            'image' => '/images/furniture/ridgley.jpg',
            'SKU' => '0000946789',
        ]);  
        DB::table('furniture')->insert([
            'category_id' => 4,
            'manufacturer_id' => 3,
            'material_id' => 9,
            'name' => 'Fortunat Extendable Dining Table',
            'price' => 799.99,
            'depth' => '48.0"',
            'height' => '30.0"',
            'width' => '66.0"',
            'cost' => 650.00,
            'description' => 'Anchor your dining room in a modern farmhouse style with this extendable dining table. Crafted of solid hardwood with laminate veneers in a white limed finish, the tabletop strikes a 48" W x 48" D (with the leaf stored) in circular silhouette, or 48" W x 66" D (with the leaf in place), with distressed edges for a charming, well-worn look. Rounding out the design, the turned pedestal base includes four moulded feet for sturdy support. Perfect for school night dinners and full-on family feasts alike, this table comfortably seats four as-is or up to six with the addition of the included lift-off leaf.',
            'color' => 'Grey',
            'image' => '/images/furniture/fortunat.jpg',
            'SKU' => '0000946788',
        ]);  
        DB::table('furniture')->insert([
            'category_id' => 4,
            'manufacturer_id' => 1,
            'material_id' => 10,
            'name' => 'Helena Dining Table',
            'price' => 599.99,
            'depth' => '45.0"',
            'height' => '30.0"',
            'width' => '45.0"',
            'cost' => 450.00,
            'description' => 'Helena Dining Table was manufactured by Medison Park Signature. Madison Park Signature collections are created using quality fabrics and special design elements providing the perfect finishing touches to your home. The rich colour palette lends a sophisticated and stylish yet refined aesthetic for the mature customer. Unique details add irresistible value to your space to give the best in affordable luxury. Madison Park Signature bed ensembles are carefully designed to address the top home decor lifestyle preferences of today’s consumer.',
            'color' => 'Grey',
            'image' => '/images/furniture/helena.jpg',
            'SKU' => '0000946787',
        ]);                                                               
        DB::table('furniture')->insert([
            'category_id' => 4,
            'manufacturer_id' => 2,
            'material_id' => 9,
            'name' => 'Itchington Dining Table',
            'price' => 559.99,
            'depth' => '48.0"',
            'height' => '30.0"',
            'width' => '48.0"',
            'cost' => 410.00,
            'description' => 'Perfect for intimate dinners and festive family gatherings alike, this traditional round dining table anchors the heart of your home in cottage-chic style! Crafted from solid rubberwood, this piece measures 48" L x 48" W x 30" H overall. It accommodates four people comfortably for a lunch time catch up with friends or a casual weekday dinner with family. To clean, we recommend using a damp cloth. Assembly is required upon arrival.',
            'color' => 'Antique White',
            'image' => '/images/furniture/itchington.jpg',
            'SKU' => '0000946786',
        ]);             
        DB::table('furniture')->insert([
            'category_id' => 4,
            'manufacturer_id' => 3,
            'material_id' => 10,
            'name' => 'Eubanks Dining Table',
            'price' => 259.99,
            'depth' => '42.0"',
            'height' => '30.0"',
            'width' => '42.0"',
            'cost' => 180.00,
            'description' => 'The heart of your entertaining ensemble is your dining table. Not only is it the spot where you serve up dinner party courses and festive family feasts, but it sets the aesthetic tone for your room and allows you to stage centerpieces that are all your own. Just take a look at this one for example: Brimming with mid-century style, its manufactured wood frame features angled legs and a circular top.',
            'color' => 'White',
            'image' => '/images/furniture/eubanks.jpg',
            'SKU' => '0000946785',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 4,
            'manufacturer_id' => 1,
            'material_id' => 9,
            'name' => 'Bradford Poplar Solid Wood Dining Table',
            'price' => 939.99,
            'depth' => '48.0"',
            'height' => '30.0"',
            'width' => '48.0"',
            'cost' => 750.00,
            'description' => 'Some of our best memories are created at our dining tables – they host our family dinners, holiday feasts and more. No matter the shape or size, they play an integral role in our home. Take this one for example: Made in the USA, this piece is crafted from solid wood and showcases a round top that rests aloft a tripod-style pedestal base, working well in a variety of aesthetics from classic to contemporary. Plus, awash in a medium brown finish, it blends easily with your existing colour scheme.',
            'color' => 'Brown',
            'image' => '/images/furniture/bradford.jpg',
            'SKU' => '0000946784',
        ]);  
        DB::table('furniture')->insert([
            'category_id' => 4,
            'manufacturer_id' => 2,
            'material_id' => 10,
            'name' => 'Brunoy Extendable Dining Table',
            'price' => 499.99,
            'depth' => '28.0"',
            'height' => '30.0"',
            'width' => '47.0"',
            'cost' => 499.99,
            'description' => 'This Extendable Dining Table features clean and modern lines adding a sophisticated look and modern edge to any room.',
            'color' => 'Grey',
            'image' => '/images/furniture/brunoy.jpg',
            'SKU' => '0000946783',
        ]);   
        DB::table('furniture')->insert([
            'category_id' => 4,
            'manufacturer_id' => 3,
            'material_id' => 9,
            'name' => 'Barrington Dining Table',
            'price' => 999.99,
            'depth' => '48.0"',
            'height' => '30.0"',
            'width' => '48.0"',
            'cost' => 690.00,
            'description' => 'More than just a dining room centerpiece, dining tables set the scene for family gatherings, holiday dinner parties, family game nights, and everyday meals alike. Take this one for example: Crafted from a blend of solid and manufactured wood, it’s founded atop a pedestal base and boasts a neutral espresso finish for a look that complements nearly any colour palette. Measuring 48" L x 48" W x 30" H, it comfortably accommodates up to four.',
            'color' => 'Brown',
            'image' => '/images/furniture/barrington.jpg',
            'SKU' => '0000946782',
        ]);
        DB::table('furniture')->insert([
            'category_id' => 4,
            'manufacturer_id' => 1,
            'material_id' => 10,
            'name' => 'Spruill Drop Leaf Solid Wood Dining Table',
            'price' => 299.99,
            'depth' => '42.0"',
            'height' => '29.0"',
            'width' => '42.0"',
            'cost' => 150.00,
            'description' => 'Spruill Drop Leaf Solid Wood Dining Table for your dining space, cottage style with this traditional country dining table. Crafted of solid wood, the round tabletop includes two drop leaves to comfortably seat two or four, while the lathed pedestal base features four simplified cabriole legs for support. Perfectly sized for smaller spaces like eat-in kitchens and dining nooks, this timeless table measures 29" H x 42" W x 42" D overall when fully expanded.',
            'color' => 'Espresso',
            'image' => '/images/furniture/spruill.jpg',
            'SKU' => '0000946781',
        ]);   
        DB::table('furniture')->insert([
            'category_id' => 4,
            'manufacturer_id' => 2,
            'material_id' => 9,
            'name' => 'Rebekah Dining Table',
            'price' => 399.99,
            'depth' => '36.0"',
            'height' => '30.0"',
            'width' => '36.0"',
            'cost' => 150.00,
            'description' => "Truly traditional, this table instantly dresses up your dining room or breakfast nook for casual meals and upscale dinner parties alike. Founded atop four cabriole legs, its base features a turned pedestal design for a touch of charming character. The 36' ' circular top accommodates up to four, allowing conversation to flow freely. Plus, it features a neutral solid finish for a look that easily fits with any ensemble's colour palette. Assembly is required for this design.",
            'color' => 'Espresso Brown',
            'image' => '/images/furniture/rebekah.jpg',
            'SKU' => '0000946780',
        ]);             

    }
}
